services:
  db:
    image: postgres:18
    container_name: booking-db
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - .:/workspace